### ISSUE TITLE
Не реагирует на сохранение

### ISSUE THREAD

**Issue by sopranofirst** [yandex-money/yandex-money-ycms-opencart3#1]
Перехожу на вкладку Маркет, ввожу обязательные поля: название магазины, доставка И так далее ... нажимаю сохранить и снова нужно вводить данные и ничего не сохраняется будто я ничего и не вписывал в обязательные поля

**Comment by Nordok** [comment]
Поддерживаю. Та же история с последней версией Opencart 3.0.2.0

**Comment by 2helper** [comment]
Не работает сохранение .
 также постоянно весит надпись сверху когда выбираю вкладки связанные с Яндекс Маркетом
 Внимательно проверьте форму на ошибки!
Версия Opencart 3.0.2.0

Есть надежда по поправите и модуль заработает ? )

**Comment by ostulov** [comment]
Добрый день!

Для решения данной проблемы обновите модуль до последней версии.

**Comment by 2helper** [comment]
Re: [yandex-money/yandex-money-ycms-opencart3] Не реагирует на сохранение (#1)



Поставил,
но уперся в одну ошибку и никак ее пройти не могу

раздел Яндекс.Метрика
все ок создал приложение oauth
нажал- Получить токен для доступа к Яндекс.Метрика
ВСЕ ПОЛУЧИЛ

раздел Заказы на маркете
делаю все ок создал приложение в oauth
все вбил- сохранил
нажал - Получить токен (нажмите после сохранения настроек)- в oauth
нажимаю Разрешить - и выкидывает на ошибку Токен yandex не получен!
сверху вот такой урл
https://tessutiesclusivi.ru/admin/index.php?route=extension/payment/yandex_money&err=Client%20not%20found&user_token=DDEWaF2gk9Bxsqbaq9FGRh4EVNPPBvid

Что это за err=Client%20not%20found ?
в админке ЯМ все сверил все ок


Вы писали 19 марта 2018 г., 17:17:00:

Проверьте, что при настройке Вы указываете адреса через https.
Полная инструкция по настройке модуля (аналогична Opencart2):
https://kassa.yandex.ru/manuals/y.cms_opencart2.html



-- 
С уважением,
Info mailto:info@tessutiesclusivi.ru
Вы писали 26 марта 2018 г., 14:31:07:





Добрый день!
Для решения данной проблемы обновите модуль до последней версии.
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or mute the thread.





-- 
С уважением,
 2helper                          mailto:2helper@mail.ru

**Comment by ostulov** [comment]
Баг с получением токена на вкладке "Заказы на Маркете" был устранен в версии v1.0.6
